# -*- coding: utf-8 -*-
"""legaldoc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIyrFr9hXHJKVGMxcc7RhoUrQvx19Fhz
"""

import gradio as gr
from transformers import pipeline
from docx import Document as DocxDocument
import PyPDF2
import os

# Initialize Granite Guardian Pipeline
granite_pipe = pipeline("text-generation", model="ibm-granite/granite-guardian-3.1-2b")

# Helper: Extract text from DOCX, PDF, or TXT
def extract_text(uploaded_file):
    ext = os.path.splitext(uploaded_file.name)[-1].lower()
    if ext == ".txt":
        return uploaded_file.read().decode(errors="ignore")
    elif ext == ".docx":
        doc = DocxDocument(uploaded_file)
        return "\n".join([para.text for para in doc.paragraphs])
    elif ext == ".pdf":
        reader = PyPDF2.PdfReader(uploaded_file)
        return "\n".join([page.extract_text() for page in reader.pages if page.extract_text()])
    else:
        return "Unsupported file type."

# Clause Simplification
def simplify_clause(text):
    messages = [
        {"role": "user", "content": f"Simplify the following clause for a layperson: {text}"}
    ]
    response = granite_pipe(messages, max_new_tokens=256)[0]["generated_text"]
    return response

# Named Entity Recognition (Mocked for Demo)
def extract_ner(text):
    messages = [
        {"role": "user", "content": f"Extract and list all legal parties, dates, obligations, monetary values, and legal terms from this text: {text}"}
    ]
    response = granite_pipe(messages, max_new_tokens=256)[0]["generated_text"]
    return response

# Clause Extraction (Very basic for demo)
def extract_clauses(text):
    # Split by newlines or basic legal section markers
    clauses = [p for p in text.split('\n') if len(p.strip().split()) > 5]
    return "\n\n".join([f"Clause {i+1}: {c}" for i, c in enumerate(clauses)])

# Document Type Classification
def classify_doc(text):
    messages = [
        {"role": "user", "content": f"Identify if this document is an NDA, lease, employment contract, service agreement, or other type: {text}"}
    ]
    response = granite_pipe(messages, max_new_tokens=48)[0]["generated_text"]
    return response

# Pipeline Function
def process_legal_doc(uploaded_file):
    text = extract_text(uploaded_file)
    if text.startswith("Unsupported file type."):
        return ("", "", "", "", text)
    simplified = simplify_clause(text[:1000])  # Use first 1000 chars for demo
    entities = extract_ner(text[:2000])        # Use first 2000 chars for entity extraction
    clauses = extract_clauses(text)
    doc_type = classify_doc(text[:2000])
    return (simplified, entities, clauses, doc_type, "Done")

# Gradio UI
interface = gr.Interface(
    fn=process_legal_doc,
    inputs=gr.File(label="Upload Legal Document (PDF, DOCX, TXT)"),
    outputs=[
        gr.Textbox(label="Simplified Clause Example"),
        gr.Textbox(label="Named Entity Recognition Result"),
        gr.Textbox(label="Extracted Clauses"),
        gr.Textbox(label="Document Type Classification"),
        gr.Textbox(label="Status")
    ],
    title="Legal Document Assistant (Powered by IBM Granite Guardian & Gradio)",
    description=("Upload a legal document to extract key entities, simplify clauses, classify document type, "
                 "and view all clauses in an interactive, user-friendly interface.")
)

if __name__ == "__main__":
    interface.launch()

!pip install python-docx PyPDF2

!pip install exceptions



!pip install transformers